AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/**/*
    - config/locales/**/*
    - config/environments/*
    - vendor/**/*
    - Gemfile
    - node_modules/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/BlockLength:
  Enabled: false
