language: ruby
dist: trusty
rvm:
  - 2.4.1

bundler_args: --jobs=2

cache: bundler

env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/iw_test

script:
  - bundle exec rake db:setup
  - bundle exec rake spec

services:
  - postgresql
addons:
  postgresql: "9.6"
