version: '3'

services:
  app:
    build: .
    ports:
    - 3000:3000
    volumes:
    - .:/app

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    environment:
    - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    volumes:
    - .:/app
    ports:
    - '3035:3035'

  postgres:
    image: postgres:latest
    ports:
    - 5432:5432
